ambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name assembly_web-api_1 -name assembly_jenkins_1"
mysql:
  image: mysql:5.7
  ports:
    - 3306:3306
  env_file:
    - ./production.env
paper-api:
  image: jetty:9.3
  volumes:
    - /home/ubuntu/twars/paper-api:/var/lib/jetty/webapps
  links:
    - mysql:mysql
  ports:
    - "8080:8080"
mongo:
  image: mongo:3.2
  ports:
    - "27017:27017"
web-api:
  image: node:5.8
  ports:
    - "3000:3000"
  volumes:
    - /home/ubuntu/twars/web-api:/var/app
  command: bash -c "cd /var/app && node app"
  links:
    - mongo:mongo
    - paper-api:paper-api
    - nginx:nginx
    - ambassador:jenkins
  env_file:
    - ./production.env
jenkins:
  build: ./twars-jenkins
  links:
    - ambassador:web-api
  env_file:
    - ./production.env
  ports:
    - "8088:8080"
  volumes:
    - .data/jenkins:/tmp/data
nginx:
  image: nginx:1.9
  ports:
    - "8888:80"
  links:
    - ambassador:web-api
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - /home/ubuntu/twars/quiz-resource:/var/fs
    - /home/ubuntu/twars/assets:/var/twars/web
